"""Add multimedia support columns

Revision ID: 7dd3cc32272f
Revises: 
Create Date: 2025-06-29 12:21:07.083107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd3cc32272f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns for multimedia support
    op.add_column('items', sa.Column('media_type', sa.String(), nullable=False, server_default='url'))
    op.add_column('items', sa.Column('content_data', sa.Text(), nullable=True))
    op.add_column('items', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('items', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('mime_type', sa.String(), nullable=True))
    op.add_column('items', sa.Column('user_context', sa.Text(), nullable=True))
    
    # Create index for media_type
    op.create_index(op.f('ix_items_media_type'), 'items', ['media_type'], unique=False)
    
    # Note: SQLite doesn't support altering column types, so we skip the column type changes
    # The existing VARCHAR and TEXT columns will work fine for our purposes
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_media_type'), table_name='items')
    op.drop_column('items', 'user_context')
    op.drop_column('items', 'mime_type')
    op.drop_column('items', 'file_size')
    op.drop_column('items', 'file_path')
    op.drop_column('items', 'content_data')
    op.drop_column('items', 'media_type')
    # ### end Alembic commands ### 